import { pgTable, text, varchar, integer, real, boolean, timestamp, jsonb, uuid } from "drizzle-orm/pg-core";

export const users = pgTable("users", {
  id: uuid("id").primaryKey().defaultRandom(),
  email: varchar("email", { length: 255 }).notNull().unique(),
  passwordHash: text("password_hash").notNull(),
  role: varchar("role", { length: 50 }).notNull(), // admin | company | tech | comercial
  name: varchar("name", { length: 255 }).notNull(),
  tenantId: varchar("tenant_id", { length: 100 }).notNull().default("nexorafield-default"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const companies = pgTable("companies", {
  id: varchar("id", { length: 100 }).primaryKey(),
  name: varchar("name", { length: 255 }).notNull(),
  email: varchar("email", { length: 255 }).notNull(),
  phone: varchar("phone", { length: 50 }),
  cnpj: varchar("cnpj", { length: 30 }),
  city: varchar("city", { length: 100 }),
  state: varchar("state", { length: 10 }),
  avatar: text("avatar"),
  segment: varchar("segment", { length: 100 }),
  referralCode: varchar("referral_code", { length: 50 }),
  referredBy: varchar("referred_by", { length: 100 }),
  referralCredits: real("referral_credits").default(0),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const technicians = pgTable("technicians", {
  id: varchar("id", { length: 100 }).primaryKey(),
  name: varchar("name", { length: 255 }).notNull(),
  cpf: varchar("cpf", { length: 20 }),
  rg: varchar("rg", { length: 30 }),
  birthDate: varchar("birth_date", { length: 20 }),
  email: varchar("email", { length: 255 }),
  phone: varchar("phone", { length: 50 }),
  whatsapp: varchar("whatsapp", { length: 50 }),
  city: varchar("city", { length: 100 }),
  state: varchar("state", { length: 10 }),
  cep: varchar("cep", { length: 20 }),
  address: text("address"),
  avatar: text("avatar"),
  nr10: boolean("nr10").default(false),
  nr35: boolean("nr35").default(false),
  nr33: boolean("nr33").default(false),
  specialties: jsonb("specialties").$type<string[]>().default([]),
  equipment: jsonb("equipment").$type<string[]>().default([]),
  availabilityDays: jsonb("availability_days").$type<string[]>().default([]),
  availabilityHours: varchar("availability_hours", { length: 50 }),
  radiusKm: real("radius_km").default(30),
  latitude: real("latitude"),
  longitude: real("longitude"),
  pixKey: varchar("pix_key", { length: 100 }),
  pixType: varchar("pix_type", { length: 50 }),
  bankName: varchar("bank_name", { length: 100 }),
  agency: varchar("agency", { length: 20 }),
  accountNumber: varchar("account_number", { length: 30 }),
  rating: real("rating").default(5.0),
  reviewsCount: integer("reviews_count").default(0),
  completedJobsCount: integer("completed_jobs_count").default(0),
  status: varchar("status", { length: 20 }).default("online"),
  documentsApproved: boolean("documents_approved").default(false),
  signedContract: boolean("signed_contract").default(false),
  points: integer("points").default(0),
  badges: jsonb("badges").$type<string[]>().default([]),
  referralCode: varchar("referral_code", { length: 50 }),
  referredBy: varchar("referred_by", { length: 100 }),
  referralCredits: real("referral_credits").default(0),
  responseTimeMin: integer("response_time_min"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const tickets = pgTable("tickets", {
  id: varchar("id", { length: 100 }).primaryKey(),
  title: varchar("title", { length: 500 }).notNull(),
  description: text("description"),
  category: varchar("category", { length: 100 }),
  specialty: varchar("specialty", { length: 100 }),
  urgency: varchar("urgency", { length: 20 }),
  date: varchar("date", { length: 20 }),
  time: varchar("time", { length: 20 }),
  cep: varchar("cep", { length: 20 }),
  city: varchar("city", { length: 100 }),
  state: varchar("state", { length: 10 }),
  address: text("address"),
  latitude: real("latitude"),
  longitude: real("longitude"),
  suggestedValue: real("suggested_value").default(0),
  deadline: varchar("deadline", { length: 50 }),
  photos: jsonb("photos").$type<string[]>().default([]),
  documents: jsonb("documents").$type<string[]>().default([]),
  status: varchar("status", { length: 50 }).notNull().default("Aberto"),
  companyId: varchar("company_id", { length: 100 }),
  assignedTechId: varchar("assigned_tech_id", { length: 100 }),
  invitedTechIds: jsonb("invited_tech_ids").$type<string[]>().default([]),
  declinedTechIds: jsonb("declined_tech_ids").$type<string[]>().default([]),
  checklist: jsonb("checklist").$type<{ item: string; completed: boolean }[]>().default([]),
  evidencePhotos: jsonb("evidence_photos").$type<string[]>().default([]),
  evidenceVideo: text("evidence_video"),
  technicalReport: text("technical_report"),
  clientSignature: text("client_signature"),
  invoiceUploaded: boolean("invoice_uploaded").default(false),
  ratingByCompany: jsonb("rating_by_company").$type<{ stars: number; comment: string } | null>(),
  ratingByTech: jsonb("rating_by_tech").$type<{ stars: number; comment: string } | null>(),
  fraudAlerts: jsonb("fraud_alerts").$type<string[]>().default([]),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const financialTransactions = pgTable("financial_transactions", {
  id: varchar("id", { length: 100 }).primaryKey(),
  ticketId: varchar("ticket_id", { length: 100 }),
  ticketTitle: varchar("ticket_title", { length: 500 }),
  companyName: varchar("company_name", { length: 255 }),
  techName: varchar("tech_name", { length: 255 }),
  totalAmount: real("total_amount").default(0),
  platformCommission: real("platform_commission").default(15),
  platformEarnings: real("platform_earnings").default(0),
  techPayout: real("tech_payout").default(0),
  paymentMethod: varchar("payment_method", { length: 20 }),
  status: varchar("status", { length: 30 }),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const aiAuditLogs = pgTable("ai_audit_logs", {
  id: varchar("id", { length: 100 }).primaryKey(),
  ticketId: varchar("ticket_id", { length: 100 }),
  type: varchar("type", { length: 50 }).notNull(),
  message: text("message").notNull(),
  details: jsonb("details"),
  timestamp: timestamp("timestamp").defaultNow().notNull(),
});

export const webhooks = pgTable("webhooks", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: varchar("name", { length: 255 }).notNull(),
  url: text("url").notNull(),
  secret: varchar("secret", { length: 255 }).notNull(),
  events: jsonb("events").$type<string[]>().notNull().default([]),
  enabled: boolean("enabled").notNull().default(true),
  lastStatus: varchar("last_status", { length: 20 }), // success | error | pending | null
  lastStatusCode: integer("last_status_code"),
  lastDeliveredAt: timestamp("last_delivered_at"),
  lastError: text("last_error"),
  deliveryCount: integer("delivery_count").notNull().default(0),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const webhookDeliveries = pgTable("webhook_deliveries", {
  id: uuid("id").primaryKey().defaultRandom(),
  webhookId: uuid("webhook_id").notNull(),
  event: varchar("event", { length: 100 }).notNull(),
  payload: jsonb("payload"),
  statusCode: integer("status_code"),
  status: varchar("status", { length: 20 }).notNull(), // success | error | pending
  responseBody: text("response_body"),
  error: text("error"),
  duration: integer("duration"), // ms
  deliveredAt: timestamp("delivered_at").defaultNow().notNull(),
});
