apiVersion: v1
kind: Namespace
metadata:
  name: nexorafield
  labels:
    app.kubernetes.io/managed-by: kubectl
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: nexorafield-db
  labels:
    app.kubernetes.io/managed-by: kubectl
---
apiVersion: v1
kind: Namespace
metadata:
  name: nexorafield-cache
  labels:
    app.kubernetes.io/managed-by: kubectl
