apiVersion: v1
kind: Service
metadata:
  name: nexora-api-svc
  namespace: nexorafield
  labels:
    app: nexora-api
spec:
  selector:
    app: nexora-api
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: nexora-api-lb
  namespace: nexorafield
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  selector:
    app: nexora-api
  ports:
    - port: 443
      targetPort: 5000
  type: LoadBalancer
